name: Terraform Resource Deployment

on:
  workflow_dispatch:

jobs:
  login:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::207752777514:role/Github-actions-role
          aws-region: eu-west-1
          role-session-name: github-session
          role-duration-seconds: 3600
